##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tra931/Aidaxtech.com/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp -R user $DEPLOYPATH

