##### THIS ALLOWS US TO DEPLOY THE SITE FROM A GIT REPO ######
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tra931/Aidaxtech.com/
    - /bin/cp .c_panel copy.yml.txt /home/tra931/Aidaxtech.com/

